import {
  Flight,
  BookingDetails,
  Command,
  FareDetail,
} from "@/lib/types/gds.type";

export const mockFlights: Flight[] = [
  {
    id: "1",
    flightNumber: "TG 322",
    airline: "TG",
    origin: "DAC",
    destination: "BKK",
    date: "15JUN",
    departureTime: "13:40",
    arrivalTime: "17:10",
    duration: "2H 30MIN",
    aircraft: "BOEING 777",
    class: "CC DC JC Z9 U9 Y9 B9 M9 H9 Q9 T9 K9 S9 V9 W9 L9",
    seats: 333,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 1633,
    connectivity: "DCA",
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 280.0,
        baseFareBDT: 34294,
        fareBasis: "Y15BDOA",
        nvb: "15JUN",
        nva: "15JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 57080,
        nuc: 280.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "TG",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "B",
        baseFareUSD: 300.0,
        baseFareBDT: 36744,
        fareBasis: "B15BDOA",
        nvb: "15JUN",
        nva: "15JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 59530,
        nuc: 300.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "TG",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "2",
    flightNumber: "TG 401",
    airline: "TG",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "19:00",
    arrivalTime: "22:20",
    duration: "2H 20MIN",
    aircraft: "BOEING 777",
    class: "CC DC JC Z9 Y9 B9 M9 H9 Q9 T9 K9 S9 V9 W9 L9",
    seats: 788,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 0,
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 320.0,
        baseFareBDT: 39194,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 62480,
        nuc: 320.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "TG",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "3",
    flightNumber: "MH 103",
    airline: "MH",
    origin: "DAC",
    destination: "BKK",
    date: "15JUN",
    departureTime: "12:30",
    arrivalTime: "18:40",
    duration: "4H 10MIN",
    aircraft: "BOEING 737MAX 8 PASSENGER",
    class: "J6 C6 D4 ZC I2 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q1 OC GL",
    seats: 7008,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 1633,
    meals: "Meal",
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 290.0,
        baseFareBDT: 35519,
        fareBasis: "Y15BDOA",
        nvb: "15JUN",
        nva: "15JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 58305,
        nuc: 290.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "4",
    flightNumber: "MH/FY 4668",
    airline: "MH/FY",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "20:15",
    arrivalTime: "21:30",
    duration: "1H 15MIN",
    aircraft: "AIRBUS A320",
    class: "Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q9 OC",
    seats: 738,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 1633,
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 310.0,
        baseFareBDT: 37969,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 60755,
        nuc: 310.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH/FY",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "5",
    flightNumber: "MH 103",
    airline: "MH",
    origin: "DAC",
    destination: "KUL",
    date: "15JUN",
    departureTime: "12:30",
    arrivalTime: "18:40",
    duration: "4H 10MIN",
    aircraft: "BOEING 737MAX 8 PASSENGER",
    class: "J6 C6 D4 ZC I2 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q1 OC GL",
    seats: 7008,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 1633,
    meals: "Meal",
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 270.0,
        baseFareBDT: 33070,
        fareBasis: "Y15BDOA",
        nvb: "22JUN",
        nva: "22JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 55856,
        nuc: 270.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "6",
    flightNumber: "MH/SQ 5845",
    airline: "MH/SQ",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "20:30",
    arrivalTime: "21:45",
    duration: "1H 15MIN",
    aircraft: "AIRBUS A330",
    class: "J4 C4 D4 ZC Y9 B9 H9 K9 M9 L9 V9 SC NC QC",
    seats: 359,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 1633,
    fareDetails: [
      {
        class: "Y",
        baseFareUSD: 330.0,
        baseFareBDT: 40418,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 63204,
        nuc: 330.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH/SQ",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "7",
    flightNumber: "SQ 246",
    airline: "SQ",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "06:00",
    arrivalTime: "11:45",
    duration: "5H 45MIN",
    aircraft: "BOEING 787",
    class: "J9 C9 D9 Z9 I9 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q9",
    seats: 423,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 2050,
    meals: "Meal",
    equipment: "WIFI",
    fareDetails: [
      {
        class: "N",
        baseFareUSD: 269.0,
        baseFareBDT: 32948,
        fareBasis: "N15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "25K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 45291,
        nuc: 269.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        brandedFare: "ECONOMY VALUE-YCLVALUE",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
        paymentFees: [
          { description: "OBFCA ANY CC", fee: 0, total: 45291 },
          {
            description: "OBFCA CC NBR BEGINS WITH 223529",
            fee: 0,
            total: 45291,
          },
        ],
      },
      {
        class: "Y",
        baseFareUSD: 350.0,
        baseFareBDT: 42868,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 55551,
        nuc: 350.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        brandedFare: "ECONOMY STANDARD-YCLSTANDARD",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "B",
        baseFareUSD: 380.0,
        baseFareBDT: 46542,
        fareBasis: "B15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 59225,
        nuc: 380.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "8",
    flightNumber: "SQ 502",
    airline: "SQ",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "08:00",
    arrivalTime: "18:30",
    duration: "10H 30MIN",
    aircraft: "BOEING 787",
    class: "J9 C9 D9 Z9 I9 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q9",
    seats: 423,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 2650,
    meals: "Meal",
    equipment: "WIFI",
    transit: {
      city: "BKK",
      arrivalTime: "11:30",
      departureTime: "13:15",
      layoverDuration: "1H 45MIN",
    },
    fareDetails: [
      {
        class: "N",
        baseFareUSD: 269.0,
        baseFareBDT: 32948,
        fareBasis: "N15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "25K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 45291,
        nuc: 269.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        brandedFare: "ECONOMY VALUE-YCLVALUE",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "Y",
        baseFareUSD: 350.0,
        baseFareBDT: 42868,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 55551,
        nuc: 350.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        brandedFare: "ECONOMY STANDARD-YCLSTANDARD",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "B",
        baseFareUSD: 380.0,
        baseFareBDT: 46542,
        fareBasis: "B15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 59225,
        nuc: 380.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "SQ",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "9",
    flightNumber: "MH 205",
    airline: "MH",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "10:00",
    arrivalTime: "20:45",
    duration: "10H 45MIN",
    aircraft: "BOEING 737MAX",
    class: "J6 C6 D4 ZC I2 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q1 OC GL",
    seats: 7008,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 2650,
    meals: "Meal",
    transit: {
      city: "KUL",
      arrivalTime: "14:40",
      departureTime: "16:20",
      layoverDuration: "1H 40MIN",
    },
    fareDetails: [
      {
        class: "N",
        baseFareUSD: 269.0,
        baseFareBDT: 32948,
        fareBasis: "N15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "25K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 45291,
        nuc: 269.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "Y",
        baseFareUSD: 350.0,
        baseFareBDT: 42868,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 55551,
        nuc: 350.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "B",
        baseFareUSD: 380.0,
        baseFareBDT: 46542,
        fareBasis: "B15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 59225,
        nuc: 380.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "MH",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
  {
    id: "10",
    flightNumber: "EK 784",
    airline: "EK",
    origin: "DAC",
    destination: "SIN",
    date: "15JUN",
    departureTime: "22:30",
    arrivalTime: "09:15",
    duration: "10H 45MIN",
    aircraft: "BOEING 777",
    class: "J8 C8 D8 Z8 I8 Y9 B9 H9 K9 M9 L9 V9 S9 N9 Q9",
    seats: 456,
    fare: 0,
    operates: "Everyday",
    onTime: "No data",
    airMiles: 2650,
    meals: "Meal",
    equipment: "WIFI",
    transit: {
      city: "DXB",
      arrivalTime: "02:15",
      departureTime: "04:30",
      layoverDuration: "2H 15MIN",
    },
    fareDetails: [
      {
        class: "N",
        baseFareUSD: 269.0,
        baseFareBDT: 32948,
        fareBasis: "N15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "25K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 45291,
        nuc: 269.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "EK",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "Y",
        baseFareUSD: 350.0,
        baseFareBDT: 42868,
        fareBasis: "Y15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 55551,
        nuc: 350.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "EK",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
      {
        class: "B",
        baseFareUSD: 380.0,
        baseFareBDT: 46542,
        fareBasis: "B15BDOA",
        nvb: "20JUN",
        nva: "20JUN",
        baggage: "30K",
        taxes: {
          BD: 500,
          UT: 4000,
          XT: 7843,
          W: 25000,
          E5: 443,
          YR: 2450,
          P8: 1225,
          P7: 1225,
        },
        totalBDT: 59225,
        nuc: 380.0,
        roe: 1.0,
        rateUsed: "1USD-122.48BDT",
        validatingCarrier: "EK",
        changeFee: true,
        refundFee: true,
        noShowFee: true,
      },
    ],
  },
];

export const commandsData: Command[] = [
  {
    type: "AVAILABILITY_CHECK",
    title: "Availability Check",
    format: "1[DD][MON][FROM][TO][AIRLINE]",
    example: "115JUNDACBKK",
    description:
      "Format: 1 (required) + Date (2 digits) + Month (3 letters) + From City (3 letters) + To City (3 letters) + Airline Code (3 letters)",
  },
  {
    type: "SEAT_SELL",
    title: "Seat Sell",
    format: "0[Number of Passenger][RBD][Serial Number]",
    example: "01Y2",
    description: "FOR Connecting Flight",
  },

  {
    type: "WPA",
    title: "Selected Class Fare Check",
    format: "WPA",
    example: "WPA",
    description: "Selected class fare check from PNR",
  },
  {
    type: "WPNCB",
    title: "Lowest Fare Check",
    format: "WPNCB",
    example: "WPNCB",
    description:
      "Lowest fare check across all available classes in the current availability results (if available)",
  },
  {
    type: "NAME_INSERT",
    title: "Name Insert",
    format: "-[Last Name]/[First Name][Space][Name Title]",
    example: "-HOSSEN/TUSHAR MR",
    description:
      "Insert name into this format for name insert. Name obviously match with your Passport. Title for example MR / MRS / MS ",
  },
  {
    type: "AGENCY_DETAILS",
    title: "Agency Details",
    format:
      "9[Space][Agency Name][Space][Agency Phone][Space][Reservation Officer Name]",
    example: "9 Flyger 01717171717 IMRAN",
    description:
      "Agency details in this format. Agency name, agency phone, reservation officer name",
  },
  {
    type: "TICKETING",
    title: "Ticketing",
    format: "7TAW/",
    example: "7TAW/",
    description: "Ticketing in this format.",
  },
  {
    type: "RECEIVED",
    title: "Received",
    format: "6[Space][Reservation Officer Name]",
    example: "6 IMRAN",
    description: "Received in this format. Reservation officer name",
  },
  {
    type: "END_RETRIEVE",
    title: "End Retrieve",
    format: "ER",
    example: "ER",
    description: "End retrieve in this format.",
  },
  {
    type: "IGNORE_RETRIEVE",
    title: "Ignore Retrieve",
    format: "IR",
    example: "IR",
    description: "Ignore retrieve in this format.",
  },
  {
    type: "PASSENGER_MOBILE_NUMBER",
    title: "Passenger Mobile Number",
    format: "3CTCM/[Passenger Mobile Number]",
    example: "3CTCM/01717171717",
    description:
      "Passenger mobile number in this format. 3CTCM/ [Passenger Mobile Number]",
  },
  {
    type: "PASSENGER_EMAIL_ADDRESS",
    title: "Passenger Email Address",
    format: "3CTCE/[Passenger Email Address]",
    example: "3CTCE/EXAMPLE//GMAIL.COM",
    description:
      "The passenger's email address should be provided in the following format: 3CTCE/[Passenger Email Address]. Note that instead of the standard @ symbol, // should be used.",
  },
  {
    type: "DOCS_INSERT",
    title: "Docs Insert",
    format:
      "3DOCS/[Passport type]/[Country Code]/[Passport Number]/[Nationality]/[Date of Birth]/[Gender]/[Passport Expiry Date]/[Passenger Name]",
    example: "3DOCS/P/BGD/A1234567890/BGD/22JUN98/M/25DEC30/HOSSEN/TUSHAR",
    description:
      "The passenger's document type should be provided in the following format: 3DOCS/[Passport type]/[Country Code]/[Passport Number]/[Nationality]/[Date of Birth]/[Gender]/[Passport Expiry Date]/[Passenger Name]",
  },
  {
    type: "PRICE_SAVE_OR_RESTORED",
    title: "Price Save or Restored",
    format: "PQ",
    example: "PQ",
    description: "Price save in this format.",
  },
  {
    type: "PRICE_CHECK",
    title: "Price Check",
    format: "*PQ",
    example: "*PQ",
    description: "Price check in this format.",
  },
  {
    type: "PRINTER_DESIGNATE",
    title: "Printer Designation",
    format: "PE*[Agency Code(PCC)]",
    example: "PE*NL1L",
    description:
      "Printer designation in this format. Agency code is the code of the agency that is printing the ticket.",
  },
  {
    type: "PRINTER_DESIGNATE_CONFIRM",
    title: "Printer Designate Confirm",
    format: "W*[Country Code]",
    example: "W*BD",
    description:
      "Printer designate confirm in this format. Country code is the country code of the country that is breaking the weight.",
  },
  {
    type: "DSIV",
    title: "DSIV (Printer Designate With PTR)",
    format: "DSIV[PTR NUMBER]",
    example: "DSIV30B6B2",
    description:
      "DSIV in this format. PTR number is the PTR number of the agency that is printing the ticket.",
  },
  {
    type: "PTR_ASSIGNED",
    title: "PTR Assigned",
    format: "PTR/[PTR NUMBER]",
    example: "PTR/30B6B2",
    description:
      "PTR assigned in this format. PTR number is the PTR number of the agency that is printing the ticket.",
  },
  {
    type: "INVOICE",
    title: "Invoice",
    format: "W'PQ1N1.1'ABG'FINVAGT'KP7",
    example: "W'PQ1N1.1'ABG'FINVAGT'KP7",
    description: "Invoice in this format.",
  },
  {
    type: "TICKET_DETAILS",
    title: "Ticket Details",
    format: "*A",
    example: "*A",
    description: "Ticket details in this format.",
  },
  {
    type: "CLEAR_SEGMENTS",
    title: "Clear All Segments",
    format: "IG or I",
    example: "IG",
    description:
      "Clear all segments from PNR then reload the page and start a new transaction",
  },
];

export const mockBooking: BookingDetails = {
  pnr: "ABC123",
  passengers: [
    {
      title: "MR",
      firstName: "JOHN",
      lastName: "DOE",
      type: "ADT",
    },
  ],
  flights: [mockFlights[0]],
  totalFare: 45000,
  status: "CONFIRMED",
  bookingDate: new Date().toISOString(),
};
